package com.libraryAdmin.consts;

public interface ErrorKeys {

    String INCORRECT_ACCOUNT_OR_PASSWORD = "INCORRECT_ACCOUNT_OR_PASSWORD";

    String SERVER_ERROR ="SERVER_ERROR";

    String UNAUTHORIZED = "UNAUTHORIZED";

    String SAME_PASSWORD = "SAME_PASSWORD";

    String INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD";

    String TRY_AGAIN_LATER = "TRY_AGAIN_LATER";

    String TRY_AGAIN_TOMORROW = "TRY_AGAIN_TOMORROW";

    String INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE";

    String PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

    String INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT";

    String NOT_FOUND = "NOT_FOUND";

    String IS_ALREADY_DELETED = "IS_ALREADY_DELETED";

    String CATEGORY_ID_ASSOCIATED_WITH_BOOK = "CATEGORY_ID_ASSOCIATED_WITH_BOOK";

    String IS_ALREADY_EXIST = "IS_ALREADY_EXIST";

    String CATEGORY_IS_ALREADY_EXIST = "CATEGORY_IS_ALREADY_EXIST";
}
